name: Deploy Streamlit App

# Trigger the workflow on pushes to the 'main' branch
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the code from the repository
    - name: Checkout code
      uses: actions/checkout@v2

    # Step 2: Set up the Python environment
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'  # Adjust this to your required version

    # Step 3: Install the required dependencies
    - name: Install dependencies
      run: |
        pip install --upgrade pip  # Ensure pip is up to date
        pip install -r requirements.txt  # Install dependencies from the requirements.txt file

    # Step 4: Run the Streamlit app
    - name: Run Streamlit app
      env:
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}  # Access the OpenAI API key from GitHub Secrets
      run: |
        streamlit run app.py  # This runs the Streamlit app
